<?php
return array(
  'catalogo_section_bg_id' => 0,
  'partner_logo_id' => 0,
  'hero_title' => 'En iQuattro Capacitación no dictamos cursos genéricos, desarrollamos capacidades técnicas aplicables a entornos críticos y reales.',
  'hero_btn_primary' => 'Explorar cursos',
  'hero_btn_schedule' => 'Ver cronograma',
  'hero_btn_event' => 'Ver Próximo Evento',
  'beneficios_title' => 'Beneficios exclusivos de formarte en iQuattro',
  'partner_title' => 'Partner oficial en formación tecnológica',
  'partner_text' => '<p>iQuattro forma parte del programa <strong>Microsoft Learning Solutions Partner</strong>, lo que nos permite impartir contenidos oficiales del fabricante, con materiales y currículas alineadas a los estándares internacionales.</p>',
  'evoluciona_title' => 'Evoluciona con una formación que genera impacto',
  'catalogo_section_title' => 'Explora nuestro catálogo de cursos',
  'catalogo_section_text' => '<p>Nuestros programas están diseñados para acompañar a personas, equipos y organizaciones en su <strong>evolución tecnológica</strong>.</p><p>Contamos con cursos, talleres y programas especializados en productividad, Microsoft 365, Azure, inteligencia artificial, seguridad digital y analítica de datos, organizados por categorías y niveles para que encuentres fácilmente lo que necesitas.</p><p>Tanto si buscas capacitarte de forma individual como si deseas formar a tu equipo, en iQuattro encontrarás <strong>rutas de aprendizaje alineadas a objetivos reales y medibles</strong>.</p>',
  'catalogo_btn' => 'Ver Catálogo de Cursos',
  'cronograma_title' => 'Próximos cursos programados',
  'cronograma_text' => '<p>Consulta el cronograma actualizado y las plazas disponibles para formación individual o grupal.</p>',
  'cronograma_btn' => 'Ver Cronograma',
  'contact_title' => 'Hablemos sobre tu próximo paso profesional',
  'contact_cta_text' => '<p>Ya sea para ti o para tu equipo, estamos listos para acompañarte.</p><p>Déjanos tus datos y te contactaremos para brindarte información clara y personalizada sobre nuestros programas de capacitación.</p>',
);
