<?php
return array(
  'hero_bg_id'    => 0,
  'contact_side_bg_id' => 0,
  'hero_title'    => 'Infraestructura crítica.|Sin concesiones.',
  'hero_desc_1'   => 'Comercializamos e implementamos las soluciones de software más especializadas del mercado para virtualización, respaldo, recuperación, almacenamiento y gestión de bases de datos. Tecnología de clase mundial, con el respaldo de iQuattro.',
  'hero_desc_2'   => '',
  'hero_btn'      => 'Ver soluciones',
  'hero_btn_2'    => 'Solicitar evaluación',
  'infra_title'   => '',
  'infra_intro'   => '',
  'infra_card_1_value' => '5',
  'infra_card_1_text'  => 'Soluciones especializadas',
  'infra_card_2_value' => '20+',
  'infra_card_2_text'  => 'Años de experiencia',
  'infra_card_3_value' => '24/7',
  'infra_card_3_text'  => 'Soporte post-implementación',
  'infra_card_4_value' => '100%',
  'infra_card_4_text'  => 'Enfoque en continuidad',
  'portfolio_title' => 'Un portafolio preciso',
  'portfolio_text'  => 'En iQuattro no buscamos cantidad — buscamos impacto. Nuestra división Data Center se especializa en <strong>cinco soluciones de software</strong> que resuelven los desafíos más críticos de la infraestructura tecnológica empresarial: respaldo y recuperación, virtualización de entornos, gestión de bases de datos, DevOps seguro y continuidad del negocio. Cada solución está respaldada por fabricantes líderes a nivel mundial y por nuestro equipo certificado.',
  'servicios_title' => 'Las herramientas que protegen tu operación',
  'servicios_intro' => '',
  'servicios_cards' => array(
    array(
      'icon' => 'respaldo.svg',
      'icon_id' => 0,
      'title' => 'Respaldo y recuperación',
      'subtitle_1' => 'Veeam Software',
      'subtitle_2' => 'Veeam Backup & Replication',
      'desc' => 'La plataforma líder mundial en protección de datos. Veeam permite respaldar, replicar y restaurar máquinas virtuales, físicas y cargas de trabajo en la nube con la mayor velocidad y confiabilidad del mercado. Garantiza continuidad del negocio con RPO y RTO de minutos, no horas.',
      'pills' => "Backup & Restore\nReplicación\nNube híbrida\nVMware / Hyper-V\nDisaster Recovery",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'virtualizacion.svg',
      'icon_id' => 0,
      'title' => 'Virtualización de escritorios',
      'subtitle_1' => 'OMNISA',
      'subtitle_2' => 'Horizon VDI by OMNISA',
      'desc' => 'Solución de virtualización de infraestructura de escritorios (VDI) que permite centralizar y gestionar entornos de trabajo desde cualquier dispositivo y ubicación, ideal para organizaciones con trabajo remoto, sucursales distribuidas o requerimientos de seguridad estrictos sobre los endpoints.',
      'pills' => "VDI\nEscritorios virtuales\nAcceso remoto seguro\nCentralización TI\nTeletrabajo",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'gestion.svg',
      'icon_id' => 0,
      'title' => 'Gestión de licencias',
      'subtitle_1' => 'SUCE',
      'subtitle_2' => 'SUCE License Manager',
      'desc' => 'Plataforma especializada en la gestión, control y optimización del ciclo de vida de licencias de software empresarial. Permite a las organizaciones tener visibilidad total de su inventario de software, evitar gastos innecesarios y cumplir con requerimientos de auditoría y compliance de manera eficiente.',
      'pills' => "SAM\nInventario de software\nCompliance\nAuditoría",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'devops.svg',
      'icon_id' => 0,
      'title' => 'DevOps & CI/CD',
      'subtitle_1' => 'GITLAB INC.',
      'subtitle_2' => 'GitLab Enterprise Edition',
      'desc' => 'La plataforma DevSecOps más completa del mercado. GitLab EE unifica el ciclo de vida completo del desarrollo de software: repositorios de código, CI/CD, seguridad integrada, gestión de proyectos y monitoreo en una sola herramienta. Implementable on-premise para máximo control y seguridad.',
      'pills' => "DevSecOps\nCI/CD\nRepositorios Git\nOn-premise\nSeguridad de código",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'snapshots.svg',
      'icon_id' => 0,
      'title' => 'Snapshots de Bases de Datos',
      'subtitle_1' => 'DB FLASHCOPY',
      'subtitle_2' => 'DB FlashCopy Snapshot Engine',
      'desc' => 'Tecnología especializada en la creación de snapshots instantáneos de bases de datos empresariales. Permite copias point-in-time sin impacto en el rendimiento de producción, acelerando las ventanas de respaldo y habilitando recuperación granular ante fallos, corrupción de datos o ataques de ransomware.',
      'pills' => "Snapshots\nPoint-in-time recovery\nZero downtime\nAnti-ransomware\nOracle / SQL / DB2",
      'btn_txt' => 'Solicitar información',
    ),
  ),
  'implementation_title' => 'Cómo implementamos cada solución',
  'implementation_cards' => array(
    array(
      'number' => '01',
      'title' => 'Diagnóstico',
      'text' => 'Evaluamos tu infraestructura actual, identificamos riesgos y definimos los requerimientos técnicos de la organización.',
    ),
    array(
      'number' => '02',
      'title' => 'Diseño',
      'text' => 'Diseñamos la arquitectura de solución más adecuada, seleccionando los productos y configuraciones correctas para tu entorno.',
    ),
    array(
      'number' => '03',
      'title' => 'Implementación',
      'text' => 'Desplegamos e integramos la solución con estándares internacionales, minimizando el impacto en la operación productiva.',
    ),
    array(
      'number' => '04',
      'title' => 'Soporte continuo',
      'text' => 'Brindamos soporte post-implementación, actualizaciones y acompañamiento técnico para garantizar continuidad operativa.',
    ),
  ),
  'soluciones_title' => 'Qué desafíos resolvemos',
  'soluciones_cards' => array(
    array(
      'icon'  => 'insignia.svg',
      'icon_id' => 0,
      'title' => 'Continuidad del negocio ante ransomware',
      'text'  => 'Combinando Veeam y DB FlashCopy, protegemos datos críticos de tu organización con respaldo inmutable y recuperación rápida ante ataques de ransomware sin pagar rescate.',
    ),
    array(
      'icon'  => 'habilitacion.svg',
      'icon_id' => 0,
      'title' => 'Habilitación de teletrabajo seguro',
      'text'  => 'Con Horizon VDI by OMNISA, los colaboradores acceden a su entorno de trabajo corporativo desde cualquier lugar, sin exponer datos sensibles en dispositivos personales.',
    ),
    array(
      'icon'  => 'aceleracion.svg',
      'icon_id' => 0,
      'title' => 'Aceleración del ciclo de desarrollo',
      'text'  => 'GitLab EE on-premise permite a los equipos de desarrollo gestionar código, pipelines y seguridad en una sola plataforma, reduciendo tiempos de entrega y errores en producción.',
    ),
    array(
      'icon'  => 'cumplimiento.svg',
      'icon_id' => 0,
      'title' => 'Cumplimiento de auditorías de software',
      'text'  => 'SUCE permite conocer exactamente qué software está instalado, cuántas licencias se usan y cuántas se desperdician, eliminando riesgos legales y optimizando el presupuesto TI.',
    ),
    array(
      'icon'  => 'soft-7.svg',
      'icon_id' => 0,
      'title' => 'Migración de bases de datos sin downtime',
      'text'  => 'DB FlashCopy genera snapshots instantáneos que permiten migrar o actualizar bases de datos de producción sin ventanas de mantenimiento extensas ni interrupción del servicio.',
    ),
    array(
      'icon'  => 'infraestructura.svg',
      'icon_id' => 0,
      'title' => 'Infraestructura multi-sede centralizada',
      'text'  => 'La combinación de Veeam y Horizon permite gestionar y proteger la infraestructura de múltiples sucursales desde un punto central, reduciendo costos operativos.',
    ),
  ),
  'fabricantes_title' => 'Fabricantes que representamos',
  'fabricantes_cards' => array(
    array('title' => 'VEEAM', 'subtitle' => 'Software'),
    array('title' => 'OMNISA', 'subtitle' => 'Horizon VDI'),
    array('title' => 'SUCE', 'subtitle' => 'License Manager'),
    array('title' => 'GITLAB', 'subtitle' => 'Enterprise Edition'),
    array('title' => 'DB FLASHCOPY', 'subtitle' => 'Snapshot Engine'),
  ),
  'contact_title'   => 'Construye una infraestructura preparada para el futuro',
  'contact_cta_text' => 'Conversemos sobre tus desafíos de infraestructura, continuidad operativa y crecimiento tecnológico.',
);
