<?php
return array(
  'hero_bg_id'    => 0,
  'contact_side_bg_id' => 0,
  'hero_title'    => 'Infraestructura crítica.|Sin concesiones.',
  'hero_desc_1'   => 'Comercializamos e implementamos las soluciones de software más especializadas del mercado para virtualización, respaldo, recuperación, almacenamiento y gestión de bases de datos. Tecnología de clase mundial, con el respaldo de iQuattro.',
  'hero_desc_2'   => '',
  'hero_btn'      => 'Ver soluciones',
  'hero_btn_2'    => 'Solicitar evaluación',
  'infra_title'   => '',
  'infra_intro'   => '',
  'infra_card_1_value' => '5',
  'infra_card_1_text'  => 'Soluciones especializadas',
  'infra_card_2_value' => '20+',
  'infra_card_2_text'  => 'Años de experiencia',
  'infra_card_3_value' => '24/7',
  'infra_card_3_text'  => 'Soporte post-implementación',
  'infra_card_4_value' => '100%',
  'infra_card_4_text'  => 'Enfoque en continuidad',
  'portfolio_title' => 'Un portafolio preciso',
  'portfolio_text'  => 'En iQuattro no buscamos cantidad — buscamos impacto. Nuestra división Data Center se especializa en <strong>cinco soluciones de software</strong> que resuelven los desafíos más críticos de la infraestructura tecnológica empresarial: respaldo y recuperación, virtualización de entornos, gestión de bases de datos, DevOps seguro y continuidad del negocio. Cada solución está respaldada por fabricantes líderes a nivel mundial y por nuestro equipo certificado.',
  'servicios_title' => 'Las herramientas que protegen tu operación',
  'servicios_intro' => '',
  'servicios_cards' => array(
    array(
      'icon' => 'respaldo-recuperacion.svg',
      'icon_id' => 0,
      'title' => 'Respaldo y recuperación',
      'subtitle_1' => 'Veeam Software',
      'subtitle_2' => 'Veeam Backup & Replication',
      'desc' => 'La plataforma líder mundial en protección de datos. Veeam permite respaldar, replicar y restaurar máquinas virtuales, físicas y cargas de trabajo en la nube con la mayor velocidad y confiabilidad del mercado. Garantiza continuidad del negocio con RPO y RTO de minutos, no horas.',
      'pills' => "Backup & Restore\nReplicación\nNube híbrida\nVMware / Hyper-V\nDisaster Recovery",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'virtualizacion-escritorios.svg',
      'icon_id' => 0,
      'title' => 'Virtualización de escritorios',
      'subtitle_1' => 'OMNISA',
      'subtitle_2' => 'Horizon VDI by OMNISA',
      'desc' => 'Solución de virtualización de infraestructura de escritorios (VDI) que permite centralizar y gestionar entornos de trabajo desde cualquier dispositivo y ubicación, ideal para organizaciones con trabajo remoto, sucursales distribuidas o requerimientos de seguridad estrictos sobre los endpoints.',
      'pills' => "VDI\nEscritorios virtuales\nAcceso remoto seguro\nCentralización TI\nTeletrabajo",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'gestion-licencias.svg',
      'icon_id' => 0,
      'title' => 'Gestión de licencias',
      'subtitle_1' => 'SUCE',
      'subtitle_2' => 'SUCE License Manager',
      'desc' => 'Plataforma especializada en la gestión, control y optimización del ciclo de vida de licencias de software empresarial. Permite a las organizaciones tener visibilidad total de su inventario de software, evitar gastos innecesarios y cumplir con requerimientos de auditoría y compliance de manera eficiente.',
      'pills' => "SAM\nInventario de software\nCompliance\nAuditoría",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'devops-cicd.svg',
      'icon_id' => 0,
      'title' => 'DevOps & CI/CD',
      'subtitle_1' => 'GITLAB INC.',
      'subtitle_2' => 'GitLab Enterprise Edition',
      'desc' => 'La plataforma DevSecOps más completa del mercado. GitLab EE unifica el ciclo de vida completo del desarrollo de software: repositorios de código, CI/CD, seguridad integrada, gestión de proyectos y monitoreo en una sola herramienta. Implementable on-premise para máximo control y seguridad.',
      'pills' => "DevSecOps\nCI/CD\nRepositorios Git\nOn-premise\nSeguridad de código",
      'btn_txt' => 'Solicitar información',
    ),
    array(
      'icon' => 'snapshots-db.svg',
      'icon_id' => 0,
      'title' => 'Snapshots de Bases de Datos',
      'subtitle_1' => 'DB FLASHCOPY',
      'subtitle_2' => 'DB FlashCopy Snapshot Engine',
      'desc' => 'Tecnología especializada en la creación de snapshots instantáneos de bases de datos empresariales. Permite copias point-in-time sin impacto en el rendimiento de producción, acelerando las ventanas de respaldo y habilitando recuperación granular ante fallos, corrupción de datos o ataques de ransomware.',
      'pills' => "Snapshots\nPoint-in-time recovery\nZero downtime\nAnti-ransomware\nOracle / SQL / DB2",
      'btn_txt' => 'Solicitar información',
    ),
  ),
  'soluciones_title' => 'Soluciones diseñadas para entornos empresariales exigentes',
  'soluciones_cards' => array(
    array(
      'title' => 'BC / DR — Continuidad y recuperación',
      'text'  => '<p>Uno de los principales retos de los negocios es la <strong>gestión y protección</strong> de grandes volúmenes de información.</p><p>En IQuattro implementamos soluciones de almacenamiento, compresión de datos, respaldos y replicación, tanto síncrona como asíncrona, que garantizan la <strong>continuidad del negocio</strong> y una <strong>recuperación eficiente</strong> ante incidentes.</p>',
    ),
    array(
      'title' => 'Gestión de Data Centers',
      'text'  => '<p>Administrar decenas de <strong>equipos y servidores críticos</strong> requiere control, monitoreo y seguridad constante.</p><p>Ofrecemos <strong>soluciones de gestión y administración de infraestructuras</strong>, incluyendo monitoreo, help desk y control operativo, para asegurar estabilidad y disponibilidad permanente.</p>',
    ),
    array(
      'title' => 'Teletrabajo y entornos distribuidos',
      'text'  => '<p>Los nuevos modelos de trabajo exigen <strong>infraestructuras flexibles y seguras.</strong></p><p>Diseñamos soluciones que permiten habilitar el teletrabajo de forma eficiente, manteniendo el control, la seguridad y el rendimiento de los sistemas corporativos.</p>',
    ),
  ),
  'contact_title'   => 'Construye una infraestructura preparada para el futuro',
  'contact_cta_text' => 'Conversemos sobre tus desafíos de infraestructura, continuidad operativa y crecimiento tecnológico.',
);
