<?php
return array(
  'somos_title' => 'Somos iQuattro: tu socio tecnológico integral',
  'somos_p1' => 'Acompañamos a empresas e instituciones en cada etapa de su evolución digital, combinando conocimiento, innovación y experiencia para ofrecer soluciones en capacitación, ciberseguridad, infraestructura, soporte y consultoría tecnológica.',
  'somos_p2' => 'Nuestro propósito es ayudarte a construir entornos más seguros, eficientes y preparados para el futuro.',
  'feature1_title' => 'Innovación contínua',
  'feature1_text' => 'Creamos soluciones que anticipan las necesidades tecnológicas de tu organización, integrando <strong>nuevas ideas, metodologías y herramientas</strong> que impulsan tu crecimiento.',
  'feature2_title' => 'Seguridad en cada paso',
  'feature2_text' => '<strong>Protegemos tus datos, procesos e infraestructura</strong> con un enfoque integral que combina prevención, respuesta y resiliencia para garantizar continuidad operativa.',
  'feature3_title' => 'Excelencia técnica',
  'feature3_text' => 'Nuestro equipo <strong>certificado y multidisciplinario</strong> ejecuta cada proyecto con precisión, rigor y calidad, asegurando resultados confiables y medibles.',
  'divisions_title' => 'Nuestras divisiones',
  'trust_title' => '¿Por qué las empresas confían en iQuattro?',
  'trust_arc_desc' => 'Formación altamente especializada. Experiencia local y alianzas globales. Infraestructura robusta con marcas líderes. Protección integral: ciberseguridad ofensiva, defensiva y respuesta. Soporte técnico certificado.',
  'trust_z_img_id' => 0,
  'trust_y_img_id' => 0,
  'allies_title' => 'Aliados tecnológicos de clase mundial',
  'contact_title' => 'Estamos listos para ayudarte',
  'contact_side_text' => 'Ya sea que busques capacitarte, fortalecer la seguridad de tu empresa o desarrollar un proyecto tecnológico, déjanos tus datos y conversemos.',
  'front_divisions' => array(
    array(
      'slug' => 'data-center',
      'label' => 'Data Center',
      'description' => 'Provisión de hardware, soluciones de software para resolver desafíos de virtualización, respaldos, comprensión de información entre otros',
      'card_class' => 'iq-div-dc',
      'image_id' => 0,
    ),
    array(
      'slug' => 'seguridad',
      'label' => 'Seguridad',
      'description' => 'Protección de datos, maximizar la continuidad del negocio, servicios como Ethical Hacking, Antivirus, Data Loss Prevention, Anti Ransomware, entre otros.',
      'card_class' => 'iq-div-seg',
      'image_id' => 0,
    ),
    array(
      'slug' => 'capacitacion',
      'label' => 'Capacitación',
      'description' => 'Programas y cursos de capacitación y rutas de certificación',
      'card_class' => 'iq-div-cap',
      'image_id' => 0,
    ),
    array(
      'slug' => 'consultoria',
      'label' => 'Consultoría',
      'description' => 'Analizamos los contextos organizacionales desde el punto de vista ampliamente estratégico hasta el profundamente técnico.',
      'card_class' => 'iq-div-cons',
      'image_id' => 0,
    ),
    array(
      'slug' => 'servicios',
      'label' => 'Servicios',
      'description' => 'Provisión de soporte técnico en los productos que representamos, servicios de Quality Assurance y Testing.',
      'card_class' => 'iq-div-serv',
      'image_id' => 0,
    ),
  ),
  'front_allies' => array(
    array('slug' => 'gitlab', 'logo_id' => 0),
    array('slug' => 'vmware', 'logo_id' => 0),
    array('slug' => 'veeam', 'logo_id' => 0),
    array('slug' => 'quest', 'logo_id' => 0),
    array('slug' => 'microsoft', 'logo_id' => 0),
    array('slug' => 'fortinet', 'logo_id' => 0),
    array('slug' => 'solarwinds', 'logo_id' => 0),
    array('slug' => 'dellemc', 'logo_id' => 0),
  ),
);
