<?php
return array(
  'hero_bg_id' => 0,
  'hero_bg_pos_x' => 'center',
  'hero_bg_pos_y' => 'center',
  'contact_side_bg_id' => 0,
  'hero_title' => 'Seguridad digital para proteger| lo que hace crecer tu negocio',
  'hero_desc'  => "Identificamos vulnerabilidades reales, evaluamos tu cumplimiento normativo y\nrespondemos ante incidentes con metodología comprobada y profesionales certificados,\nantes de que el daño sea irreversible.",
  'hero_btn'   => 'Solicitar evaluación',
  'que_protegemos_title' => 'Servicio principal',
  'que_protegemos_intro' => 'Simulamos ataques reales contra tus sistemas, redes y aplicaciones con el mismo arsenal que usa un atacante, pero con autorización y metodología controlada. El resultado: conoces exactamente dónde estás expuesto y cómo corregirlo, antes de que alguien con malas intenciones lo descubra.',
  'que_protegemos_points' => "Penetration Testing de redes internas y perimetrales\nEvaluación de aplicaciones web y APIs (OWASP Top 10)\nPruebas de ingeniería social y phishing controlado\nRevisión de Active Directory, privilegios y credenciales\nInforme ejecutivo + técnico con plan de remediación priorizado",
  'que_protegemos_btn' => 'Solicitar Ethical Hacking',
  'seguridad_cards' => array(
    array('icon' => 'ethical.svg', 'icon_id' => 0, 'title' => 'Ethical Hacking', 'desc' => ''),
  ),
  'ejecucion_title' => 'Cómo lo ejecutamos',
  'ejecucion_cards' => array(
    array('number' => '01', 'title' => 'Alcance y autorización', 'desc' => 'Definimos los sistemas objetivo, restricciones operativas y firmamos el contrato de autorización. Sin esto, no hay hacking ético.'),
    array('number' => '02', 'title' => 'Reconocimiento y OSINT', 'desc' => 'Recopilamos toda información pública: dominios, IPs, tecnologías expuestas, empleados y credenciales filtradas en la dark web.'),
    array('number' => '03', 'title' => 'Escaneo y enumeración', 'desc' => 'Identificamos servicios activos, versiones vulnerables y vectores de ataque mediante herramientas especializadas y análisis manual.'),
    array('number' => '04', 'title' => 'Explotación controlada', 'desc' => 'Demostramos el impacto real de cada vulnerabilidad con control total para no afectar la operación productiva del cliente.'),
    array('number' => '05', 'title' => 'Reporte y remediación', 'desc' => 'Entregamos hallazgos clasificados por criticidad (CVSS), con evidencia y un plan de remediación priorizado para equipo técnico y dirección.'),
  ),
  'servicios_complementarios_title' => 'Servicios complementarios',
  'servicios_complementarios_intro' => 'Cobertura completa del ciclo de seguridad.',
  'servicios_complementarios_cards' => array(
    array(
      'icon' => 'insignia.svg',
      'icon_id' => 0,
      'title' => 'Evaluación de Cumplimiento Normativo',
      'desc' => 'Analizamos el estado real de tu organización frente a los marcos regulatorios y estándares de seguridad aplicables, identificando brechas y definiendo un plan de acción concreto para alcanzar y mantener el cumplimiento.',
      'points' => "Evaluación de controles frente a normativa ASFI y ADSIB (Bolivia)\nAnálisis de brecha (gap analysis) contra ISO 27001 y NIST CSF\nRevisión de políticas, procedimientos y controles existentes\nHoja de ruta con priorización de controles críticos\nAcompañamiento en procesos de auditoría regulatoria",
      'btn_txt' => 'Solicitar evaluación',
    ),
    array(
      'icon' => 'flash.svg',
      'icon_id' => 0,
      'title' => 'Respuesta a Incidentes de Seguridad',
      'desc' => 'Cuando ocurre un incidente, cada minuto importa. Nuestro equipo actúa con rapidez para contener la amenaza, preservar evidencia, determinar el alcance del daño y restablecer la operación de forma segura y documentada.',
      'points' => "Contención y erradicación de amenazas activas (ransomware, malware)\nAnálisis forense digital y preservación de evidencia\nDeterminación del vector de ataque y alcance de la brecha\nRecuperación segura y endurecimiento post incidente\nInforme de incidente para reguladores y alta dirección",
      'btn_txt' => 'Contactar ahora',
    ),
  ),
  'estandares_title' => 'Trabajamos bajo estándares internacionales',
  'estandares_intro' => 'Todos nuestros servicios se ejecutan con metodologías reconocidas globalmente, alineadas a la normativa regulatoria boliviana vigente.',
  'estandares_cards' => array(
    array('title' => 'OWASP', 'subtitle' => 'Top 10 Web Application Security Risks', 'detail' => 'Aplicaciones web y APIs'),
    array('title' => 'PTES', 'subtitle' => 'Penetration Testing Execution Standard', 'detail' => 'Ethical Hacking'),
    array('title' => 'MITRE ATT&CK', 'subtitle' => 'Tácticas y técnicas de adversarios reales', 'detail' => 'Threat modeling'),
    array('title' => 'ISO 27001', 'subtitle' => 'Gestión de Seguridad de la Información', 'detail' => 'Cumplimiento normativo'),
    array('title' => 'NIST CSF', 'subtitle' => 'Cybersecurity Framework v2.0', 'detail' => 'Evaluación y madurez'),
    array('title' => 'ASFI', 'subtitle' => 'Reglamento de Seguridad Informática', 'detail' => 'Sector financiero Bolivia'),
    array('title' => 'ADSIB', 'subtitle' => 'Normativa TIC para entidades del Estado', 'detail' => 'Sector público Bolivia'),
  ),
  'experiencia_title' => 'Experiencia que respalda cada servicio',
  'experiencia_cards' => array(
    array('icon' => 'insignia.svg', 'icon_id' => 0, 'stat' => '20+', 'desc' => 'Años de experiencia en seguridad TI'),
    array('icon' => 'insignia2.svg', 'icon_id' => 0, 'stat' => '100%', 'desc' => 'Profesionales certificados'),
    array('icon' => 'people.svg', 'icon_id' => 0, 'stat' => '50+', 'desc' => 'Organizaciones evaluadas'),
    array('icon' => 'flash.svg', 'icon_id' => 0, 'stat' => '72h', 'desc' => 'Tiempo máximo de respuesta a incidentes'),
  ),
  'contact_title' => 'Protege hoy la información que no puedes perder mañana',
  'contact_cta_text' => 'Evalúa el nivel de seguridad de tu organización y define una estrategia sólida con el acompañamiento de expertos.',
);
